apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: test
spec:
  rules:
    - name: test
      match:
        all:
          - resources:
              kinds:
                - sparkoperator.k8s.io/v1beta2/SparkApplication
              operations:
                - CREATE
      context:
        - name: driverLabels
          variable:
            value: "{{ request.object.spec.driver.labels || `{}`}}"
        - name: driverLabelsConfValues3
          variable:
            value: "{{ driverLabels | values(@) }}"
      generate:
        apiVersion: v1
        kind: ConfigMap
        namespace: "default"
        name: test
        data:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: test
          data:
            qi: "join(``, {{ driverLabelsConfValues3 }})"