github:
  description: "Apache Spark Kubernetes Operator"
  homepage: https://apache.github.io/spark-kubernetes-operator/
  features:
    issues: true
  labels:
    - java
    - spark
    - kubernetes
    - operator
  enabled_merge_buttons:
    merge: false
    squash: true
    rebase: true
  ghp_branch: gh-pages
  ghp_path: /
  autolink_jira: SPARK

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  pullrequests: reviews@spark.apache.org
  issues: reviews@spark.apache.org
  commits: commits@spark.apache.org
  jira_options: link label
