name: Publish Snapshot Image

on:
  schedule:
  - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      branch:
        description: 'list of branches to publish (JSON)'
        required: true
        # keep in sync with default value of strategy matrix 'branch'
        default: '["main"]'

permissions:
  contents: read

jobs:
  publish-snapshot-image:
    if: ${{ startsWith(github.repository, 'apache/') }}
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        # keep in sync with default value of workflow_dispatch input 'branch'
        branch: ${{ fromJSON( inputs.branch || '["main"]' ) }}
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e
    - name: Login to Docker Hub
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        ref: ${{ matrix.branch }}
    - name: Build and push
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
      with:
        # build cache on Github Actions, See: https://docs.docker.com/build/cache/backends/gha/#using-dockerbuild-push-action
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: build-tools/docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: apache/spark-kubernetes-operator:${{ matrix.branch }}-snapshot
